### ISSUE TITLE
atoll wall has missing textures

### ISSUE THREAD

**Issue by Aloqas** [open-goal/jak-project#2908]
![jak2_2023-08-16T18-59-12](https://github.com/open-goal/jak-project/assets/102683375/45145966-364d-4fe9-8c6b-ffee9fbbff24)
checked on PCSX2 and the original game had it too but without the grass

**Comment by water111** [comment]
PCSX2 for reference:
![image](https://github.com/open-goal/jak-project/assets/48171810/147448e6-8400-4ff9-845e-2beb060c9e95)

maybe the texture is actually just missing here, and we need to handle this in opengoal? I'll take a look

**Comment by water111** [comment]
yeah, looks like they should just be untextured - here's a fixed opengoal version (at a slightly different time of day from the PCSX2 screenshot)
![image](https://github.com/open-goal/jak-project/assets/48171810/e3cde839-8441-4180-bc42-894859fdad83)

**Comment by water111** [comment]
Should be fixed now, you'll need to recompile and extract to see the change

**Comment by Heimdyl** [comment]
Issue still persists as of **0.2.2**
![image](https://github.com/open-goal/jak-project/assets/138115856/6e978700-410d-4fb9-96ac-99dd31a5f092)

**Comment by Hat-Kid** [comment]
This is what it's supposed to look like.

**Comment by Heimdyl** [comment]
> This is what it's supposed to look like.

I doubt that.
(Timestamped): https://youtu.be/VH-igmeFD0U?si=usNsk0lQs33pjyha&t=3178
![image](https://github.com/open-goal/jak-project/assets/138115856/ff11d93e-b2ff-487f-bcf5-4ed23fba64a4)

**Comment by ManDude** [comment]
Make sure to also open an issue for when Kor's face isn't blacked out.

**Comment by Heimdyl** [comment]
Relevance?
